version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - ./master.key:/rails/config/master.key
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"